### ISSUE TITLE
ios 静默消息可能会闪退

### ISSUE THREAD

**Issue by chentogit** [react-native-hero/umeng-push#10]
```
// 系统版本 >= 10，只能是静默推送
    // 静默推送时，message 必然是字符串，但是必须为空，否则会变成通知
    else if ([message isKindOfClass:[NSDictionary class]] || (message != nil && message.length == 0)) {
        if (PUSH_INSTANCE != nil) {
            [PUSH_INSTANCE sendEventWithName:@"message" body:body];
        }
    }
```

这块地方有可能是NSDictionary对象，调用length会闪退

**Comment by musicode** [comment]
你截取的这段代码，NSDictionary 分支不会执行 message.length 啊

**Comment by chentogit** [comment]
> 你截取的这段代码，NSDictionary 分支不会执行 message.length 啊

**Comment by chentogit** [comment]
> 你截取的这段代码，NSDictionary 分支不会执行 message.length 啊

那就反过来先判断下message是不是NSString对象,是的话再调用length方法。iOS里面NSDictionary对象直接调length方法是会闪退的。我们的后台要发静默消息，结果message里面装了一堆数据，变成通知了

**Comment by chentogit** [comment]
> > 你截取的这段代码，NSDictionary 分支不会执行 message.length 啊
> 
> 那就反过来先判断下message是不是NSString对象,是的话再调用length方法。iOS里面NSDictionary对象直接调length方法是会闪退的。我们的后台要发静默消息，结果message里面装了一堆数据，变成通知了

可能是我误会你的意思了，截取的那段代码是我自己改过之后的，现在库里的代码是没有NSDictionary的判断的
