### ISSUE TITLE
安卓厂商通道

### ISSUE THREAD

**Issue by tanjiaweiGitHub** [react-native-hero/umeng-push#3]
1. 测试设备： 红米 荣耀 vivo oppo各一款机型
2. 进行厂商通道推送测试， 只有vivo收到了厂商推送消息
能提供一个简单的各机型均可以成功进行厂商推送的react native demo吗

**Comment by musicode** [comment]
参考 readme 安卓部分，然后重点是要配置厂商后台，参考官方[文档](https://developer.umeng.com/docs/66632/detail/98589)即可。

我这华为和荣耀肯定没问题，其他手机没测过，应该正常（不然早就有人投诉了...）

**Comment by chentogit** [comment]
> 1. 测试设备： 红米 荣耀 vivo oppo各一款机型
> 2. 进行厂商通道推送测试， 只有vivo收到了厂商推送消息
>    能提供一个简单的各机型均可以成功进行厂商推送的react native demo吗

红米可以参考这篇文章：https://blog.csdn.net/chinaboyliusir/article/details/107459533
华为我也是折腾了好几天收不到消息，sha加密等都配置了没用，其他品牌还没试过。
