### ISSUE TITLE
大佬这个目前还维护吗？有个问题请帮帮我

### ISSUE THREAD

**Issue by fadeli1** [react-native-hero/umeng-push#5]
我将友盟相关包升级到最新版后，编译出现Unresolved reference: setNotificaitonOnForeground这个错，kotlin版的代码有点不懂。。

**Comment by fadeli1** [comment]
想了个临时方案，注释了代码，最后成功了，测试了推送可以，明天测试厂商集成推送。
感谢作者提供这么好的插件

**Comment by musicode** [comment]
不能升级到友盟最新版，那个版本有 bug，你就用这个库提供的默认版本就行

**Comment by musicode** [comment]
不能升级到友盟最新版，那个版本有 bug，你就用这个库提供的默认版本就行

**Comment by fadeli1** [comment]
@musicode 
maven { url 'https://dl.bintray.com/umsdk/release' }
这个仓库没有指定的版本文件了

友盟的好像只有最新版的仓库。。。

**Comment by fadeli1** [comment]
@musicode
不升级的话，maven仓库不可用
maven { url 'https://dl.bintray.com/umsdk/release' }

**Comment by musicode** [comment]
不太理解你说的不可用是什么意思，如果你按我写的 readme 配置完了，按理说不存在自己写 umeng 版本号的问题，不知道你在使用中发生了什么...

**Comment by musicode** [comment]
我看友盟在我上次更新之后又发了一个新版本，连仓库都迁移了，我试着升级一下看看，没问题再来升级这个库

**Comment by musicode** [comment]
升级 @react-native-hero/umeng-push@0.1.6

修改 `android/build.gradle`，如下：

```
allprojects {
    repositories {
        // 确保添加了华为和友盟仓库
        maven { url 'https://developer.huawei.com/repo/'}
        maven { url 'https://repo1.maven.org/maven2/' }
    }
}
```

强烈建议不要自己折腾友盟最新版本，跟着这个库走就行，友盟最新版本的质量非常不可控，我今天跟他客服耗了一下午才跑通，要不是我今天正好没事做，我是真的不想去升级。

**Comment by musicode** [comment]
以后如果友盟没写某个版本强烈建议升级，或当前使用的这个版本被友盟停止维护了，请不要来提 issue 说升级的事，真的被友盟代码质量伤到了，谁 TM 想升级自己升级去。

**Comment by fadeli1** [comment]
@musicode 谢谢，辛苦了

**Comment by 349989153** [comment]
哎，还想来问问RN的友盟关于合规升级的事儿

**Comment by musicode** [comment]
@349989153 看 readme 的 usage，注释写的很清楚
